// <auto-generated />
using System;
using Calendar.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calendar.Web.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Calendar.Entities.Tables.ToDoTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("ToDoTasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            DueDate = new DateTimeOffset(new DateTime(2021, 3, 13, 14, 0, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Text = "Clean house"
                        },
                        new
                        {
                            TaskId = 2,
                            DueDate = new DateTimeOffset(new DateTime(2021, 3, 14, 14, 30, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Text = "Deploy project"
                        },
                        new
                        {
                            TaskId = 3,
                            DueDate = new DateTimeOffset(new DateTime(2021, 3, 13, 15, 30, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Text = "Do some management"
                        },
                        new
                        {
                            TaskId = 4,
                            DueDate = new DateTimeOffset(new DateTime(2021, 3, 14, 12, 0, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Text = "Go shopping"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
